services:
  tf:
    build: ./tf
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia

  torch:
    build: ./torch
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia